# Generated by Django 5.0.1 on 2024-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
